<?php

define('FLAT_AUTH_THRESHOLD_EXPIRE', 60 * 5);
define('FLAT_AUTH_THRESHOLD_DELETE', 60 * 10);
define('FLAT_AUTH_MAX_ERROR_COUNT', 10);
define('FLAT_AUTH_MAX_USAGE_COUNT', 10);

function flat_auth_menu() {

  $items = [];
  $items['flat_auth'] = [

    'type' => MENU_LOCAL_TASK,
    'title' => 'Flat Auth - Check Token',
    'description' => 'Flat Auth - Check Token',
    'page callback' => 'flat_auth_check_token',
    'access callback' => true,
  ];

  $items['flat_auth/create'] = [

    'type' => MENU_LOCAL_TASK,
    'title' => 'Flat Auth - Create Token',
    'description' => 'Flat Auth - Create Token',
    'page callback' => 'flat_auth_create_token',
    'access callback' => true,
  ];

  $items['flat_auth/renew'] = [

    'type' => MENU_LOCAL_TASK,
    'title' => 'Flat Auth - Renew Token',
    'description' => 'Flat Auth - Renew Token',
    'page callback' => 'flat_auth_renew_token',
    'access callback' => true,
  ];


  $items['admin/config/flat_deposit/flat_auth'] = [

    'title' => 'FLAT Auth Configuration',
    'description' => 'FLAT Auth Configuration',
    'access arguments' => array('admin deposit module'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('flat_auth_admin_form'),
    'file' => 'includes/admin.inc',
    'weight' => 999,
  ];

  return $items;
}

function flat_auth_authtoken_type_info() {

    return [

        'flat_auth' => [

            'entity type' => 'user',
            'label' => 'FLAT Auth',
            'settings' => [

                'threshold expire' => variable_get('flat_auth_expiration_time', FLAT_AUTH_THRESHOLD_EXPIRE),
                'threshold delete' => variable_get('flat_auth_deletion_time', FLAT_AUTH_THRESHOLD_DELETE),
                'max error count'  => variable_get('flat_auth_max_error_count', FLAT_AUTH_MAX_ERROR_COUNT),
                'max usage count'  => variable_get('flat_auth_max_usage_count', FLAT_AUTH_MAX_USAGE_COUNT),
            ],
            'generate token callback' => 'flat_auth_generate_token',
        ],
    ];
}

/**
 * Generate an unique token
 *
 * @return string
 */
function flat_auth_generate_token() {
    return drupal_strtoupper(bin2hex(drupal_random_bytes(16)));
}

/**
 * Get the bearer token
 */
function flat_auth_get_bearer_token() {

    $bearer_token = NULL;

    if (isset($_SERVER['HTTP_AUTHORIZATION'])) {
        $bearer_token = str_replace('Bearer ', '', $_SERVER['HTTP_AUTHORIZATION']);
    } elseif (isset($_SERVER['HTTP_X_AUTHORIZATION'])) {
        $bearer_token = str_replace('Bearer ', '', $_SERVER['HTTP_X_AUTHORIZATION']);
    } elseif (isset($_SERVER['REDIRECT_HTTP_AUTHORIZATION'])) {
        $bearer_token = str_replace('Bearer ', '', $_SERVER['REDIRECT_HTTP_AUTHORIZATION']);
    }

    return $bearer_token;
}

function flat_auth_check_token() {

    $token = flat_auth_get_bearer_token();
    $authtoken = authtoken_load($token);

    if ($authtoken) {

        if (authtoken_authenticate($authtoken->token(), [$authtoken->type()])) {

            return drupal_json_output([

                'type' => 'success',
                'expiration_time' => variable_get('flat_auth_expiration_time', FLAT_AUTH_THRESHOLD_EXPIRE),
                'deletion_time' => variable_get('flat_auth_deletion_time', FLAT_AUTH_THRESHOLD_DELETE),
            ]);
        }
    }

    return drupal_json_output([

        'type' => 'error',
        'message' => 'Invalid token',
    ]);
}

function flat_auth_get_token() {

    global $user;
    return flat_auth_get_token_for_user($user);
}

function flat_auth_get_token_for_user($user) {

    $entity = $user;

    $authtoken = authtoken_assign('flat_auth', $user, $entity);
    return $authtoken->token();
}

function flat_auth_renew_token() {

    $token = flat_auth_get_bearer_token();
    $authtoken = authtoken_load($token);

    if ($authtoken) {

        if (authtoken_authenticate($authtoken->token(), [$authtoken->type()])) {

            if ($user = user_load($authtoken->uid())) {

                $token = flat_auth_get_token_for_user($user);
                drupal_add_http_header('Authorization', 'Bearer ' . $token);

                return drupal_json_output([

                    'type' => 'success',
                    'expiration_time' => variable_get('flat_auth_expiration_time', FLAT_AUTH_THRESHOLD_EXPIRE),
                    'deletion_time' => variable_get('flat_auth_deletion_time', FLAT_AUTH_THRESHOLD_DELETE),
                ]);
            }
        }
    }

    return drupal_json_output([

        'type' => 'error',
        'message' => 'Invalid token',
    ]);
}

function flat_auth_create_token() {

    return drupal_json_output([
        'token' => flat_auth_get_token(),
    ]);
}